[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]

[start]
cmd = "python main.py"
