[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python agriweb_hebergement_gratuit.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { ENVIRONMENT = "production", DEBUG = "false" }
